#!/usr/bin/env node
/**
 *   npm run forge -- init <slug>        create the empty tree for a new topic
 *   npm run forge -- sources <slug>     fold research shards into sources.json
 *   npm run forge -- sources <slug> --verify  re-fetch each source, check its excerpts
 *   npm run forge -- check <slug>       rule on the draft map without applying it
 *   npm run forge -- apply <slug>       project the approved map onto disk
 *   npm run forge -- status [<slug>]    what is still owed, and what to run next
 *   npm run forge -- eval <slug> <cNN>  run a challenge's eval set (--reference for the solution)
 *   npm run forge -- progress <slug>    create the learner's progress file if it is missing
 *   npm run forge -- promote <slug>     draft to validated, if the validator agrees
 *   npm run forge -- verify <slug>      stamp the verification agents' rulings into frontmatter
 *
 * These are the mechanical steps of the forge-generate skill. They are a CLI
 * rather than skill prose because a program that writes the same tree every time
 * is worth more than a model that remembers the contract most of the time.
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { SLUG, sourcesFileSchema } from "./contract.ts";
import {
  applyPlan,
  checkPlanFile,
  initTopic,
  mergeSources,
  promoteToValidated,
  recordVerdicts,
  statusOf,
  evalChallenge,
  initProgress,
} from "./forge-scaffold.ts";
import { checkSources, fetchText } from "./source-check.ts";

const USAGE = `Usage:
  npm run forge -- init <slug>
  npm run forge -- sources <slug> [--verify]
  npm run forge -- check <slug> [--approved]
  npm run forge -- apply <slug>
  npm run forge -- status [<slug> | --all]
  npm run forge -- eval <slug> <challengeId> [--reference]
  npm run forge -- progress <slug>
  npm run forge -- promote <slug>
  npm run forge -- verify <slug>`;

const args = process.argv.slice(2);
const command = args[0];
const rest = args.slice(1).filter((a) => !a.startsWith("--"));
const all = args.includes("--all");
const root = process.cwd();

function requireSlug(): string {
  const slug = rest[0];
  if (!slug) fail(`${command} needs a topic slug`);
  if (!SLUG.test(slug)) fail(`"${slug}" is not a valid slug (${SLUG})`);
  return slug;
}

function fail(message: string): never {
  console.error(`✗ ${message}\n\n${USAGE}`);
  process.exit(2);
}

function reportProblems(label: string, problems: string[]): never {
  console.error(`✗ ${label}: ${problems.length} problem(s)`);
  for (const problem of problems) console.error(`  ${problem}`);
  process.exit(1);
}

/**
 * Re-fetches every source and reports whether its pinned excerpts are still in it.
 * Advisory: a miss is a lead, not a verdict, because rendered documents differ from
 * their source text in ways an honest quotation cannot avoid. A source that is
 * entirely missing is the finding worth acting on.
 */
async function verifyPinnedQuotes(root: string, slug: string): Promise<void> {
  const file = join(root, "topics", slug, "sources.json");
  if (!existsSync(file)) fail(`${file} does not exist; run the research stage first`);
  const parsed = sourcesFileSchema.safeParse(JSON.parse(readFileSync(file, "utf8")));
  if (!parsed.success) reportProblems(file, parsed.error.issues.map((i) => i.message));
  const checks = await checkSources(parsed.data.sources, fetchText);

  let missing = 0;
  let spacing = 0;
  let verbatim = 0;
  for (const check of checks) {
    if (!check.fetched) {
      console.log(`✗ ${check.id} could not be fetched (${check.note}) — ${check.url}`);
      continue;
    }
    const gone = check.excerpts.filter((e) => e.verdict === "missing");
    verbatim += check.excerpts.filter((e) => e.verdict === "verbatim").length;
    spacing += check.excerpts.filter((e) => e.verdict === "spacing").length;
    missing += gone.length;
    const mark = gone.length === check.excerpts.length ? "✗" : gone.length ? "!" : "✓";
    console.log(`${mark} ${check.id} ${check.excerpts.length - gone.length}/${check.excerpts.length} — ${check.url}`);
    for (const excerpt of gone) console.log(`    not found: ${check.id}.${excerpt.key}  ${excerpt.locator}`);
  }

  console.log(`\n${verbatim} verbatim, ${spacing} verbatim apart from formatting, ${missing} not found`);
  if (missing) {
    console.log(
      "A miss is a lead. Read the excerpt against the page before changing anything: list\n" +
        "numbering, table rules, and entities are generated by the renderer and are absent from\n" +
        "the document text. A source where nothing at all was found is the one to act on.",
    );
  }
}

function topicSlugs(): string[] {
  const dir = join(root, "topics");
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith("."))
    .map((e) => e.name)
    .sort();
}

switch (command) {
  case "init": {
    const slug = requireSlug();
    const result = initTopic(root, slug);
    console.log(`✓ topics/${slug}: tree created`);
    for (const path of result.created) console.log(`  + ${path}`);
    console.log("\nNext: run the research stage, then: npm run forge -- sources " + slug);
    break;
  }

  case "sources": {
    const slug = requireSlug();
    if (args.includes("--verify")) {
      await verifyPinnedQuotes(root, slug);
      break;
    }
    const result = mergeSources(root, slug);
    if (result.problems.length) reportProblems(`topics/${slug}/sources.json`, result.problems);
    if (!result.shards.length) {
      console.error(`✗ .forge-cache/${slug}/research/ holds no shards; nothing to merge`);
      process.exit(1);
    }
    console.log(
      `✓ topics/${slug}/sources.json: ${result.sources} source(s) (${result.primary} primary), ${result.excerpts} excerpt(s) from ${result.shards.length} shard(s)`,
    );
    if (result.folded) {
      console.log(`  ${result.folded} source entr(ies) folded into one document each`);
    }
    if (result.merged) console.log(`  ${result.merged} duplicate excerpt(s) folded together`);
    console.log(`  shards: ${result.shards.join(", ")}`);
    break;
  }

  case "check": {
    const slug = requireSlug();
    const result = checkPlanFile(root, slug, args.includes("--approved"));
    if (result.problems.length) reportProblems(result.path, result.problems);
    console.log(
      `✓ ${result.path}: ${result.chapters} chapter(s), ${result.challenges} challenge(s), ${result.concepts} concept(s), ${result.allocated} excerpt(s) allocated`,
    );
    break;
  }

  case "apply": {
    const slug = requireSlug();
    const result = applyPlan(root, slug);
    if (result.problems.length) reportProblems(`.forge-cache/${slug}/map.approved.json`, result.problems);
    console.log(`✓ topics/${slug}: plan applied`);
    for (const path of result.written) console.log(`  + ${path}`);
    for (const path of result.refreshed) console.log(`  ~ ${path}`);
    for (const path of result.orphans) console.log(`  ? ${path} is not in the plan; move or delete it by hand`);
    break;
  }

  case "status": {
    const slugs = all || !rest.length ? topicSlugs() : [requireSlug()];
    if (!slugs.length) {
      console.log("No topics under topics/ yet.");
      break;
    }
    for (const slug of slugs) {
      const status = statusOf(root, slug);
      console.log(`topics/${slug} — stage: ${status.stage}`);
      for (const item of status.outstanding) {
        const owed = item.ids.length ? `  outstanding: ${item.ids.join(" ")}` : "";
        console.log(`  ${item.kind.padEnd(11)} ${item.done}/${item.total}${owed}`);
      }
      const { total, uncited, unallocated } = status.excerpts;
      console.log(`  excerpts    ${total - uncited.length}/${total} cited`);
      if (uncited.length) console.log(`    uncited: ${uncited.join(" ")}`);
      if (unallocated.length) console.log(`    not allocated to any chapter: ${unallocated.join(" ")}`);
      for (const missing of status.missingCitations) {
        console.log(`    ${missing.chapter} owes citations for: ${missing.refs.join(" ")}`);
      }
      if (!status.map.approved) {
        console.log(`  map        ${status.map.draft ? "written, awaiting approval" : "not written"}`);
      }
      console.log(`  next: ${status.next}\n`);
    }
    break;
  }

  case "eval": {
    const slug = requireSlug();
    const challengeId = rest[1];
    if (!challengeId) fail("eval needs a challenge id, e.g. c02");
    const result = evalChallenge(root, slug, challengeId, args.includes("--reference"));
    if (result.problems.length && !result.ran) reportProblems(`${slug}/${challengeId}`, result.problems);

    console.log(`${result.passed ? "✓" : "✗"} ${challengeId} against ${result.against}: ${result.command}`);
    for (const m of result.metrics) {
      const shown = m.value === undefined ? "not reported" : String(m.value);
      const bar = `${m.direction === "gte" ? ">=" : "<="} ${m.threshold}`;
      console.log(`  ${m.ok ? "✓" : "✗"} ${m.name.padEnd(20)} ${shown.padStart(12)}  ${bar}`);
    }
    for (const problem of result.problems) console.log(`  ! ${problem}`);
    if (result.output) console.log(result.output.replace(/^/gm, "  "));
    if (!result.passed) process.exit(1);
    break;
  }

  case "progress": {
    const slug = requireSlug();
    const created = initProgress(root, slug);
    console.log(
      created
        ? `✓ topics/${slug}/.state/progress.json created`
        : `✓ topics/${slug}/.state/progress.json already exists; left alone`,
    );
    break;
  }

  case "promote": {
    const slug = requireSlug();
    const result = promoteToValidated(root, slug);
    if (result.promoted) {
      console.log(`✓ topics/${slug}: status is now validated`);
      break;
    }
    if (!result.errors && !result.warnings) {
      console.log(`✓ topics/${slug}: already verified; leaving it there`);
      break;
    }
    console.error(
      `✗ topics/${slug}: not promoted (${result.errors} error(s), ${result.warnings} warning(s) under --strict)`,
    );
    console.error(`  see: npm run validate -- topics/${slug} --strict`);
    process.exit(1);
  }

  case "verify": {
    const slug = requireSlug();
    const result = recordVerdicts(root, slug);

    for (const row of result.chapters) {
      const mark = row.status === "verified" ? "✓" : row.faithfulness === "pending" || row.critique === "pending" ? "·" : "✗";
      const claims = row.claims ? `${row.claims} claim(s)` : "no audit";
      const blocking = row.blocking ? `, ${row.blocking} blocking` : "";
      console.log(
        `  ${mark} ${row.chapter.padEnd(6)} faithfulness ${row.faithfulness.padEnd(7)} critique ${row.critique.padEnd(7)} ${claims}${blocking}`,
      );
    }
    for (const path of result.stamped) console.log(`  + ${path}`);

    if (result.problems.length) {
      console.error(`✗ topics/${slug}: ${result.problems.length} problem(s)`);
      for (const problem of result.problems) console.error(`  ${problem}`);
      process.exit(1);
    }

    const pending = result.chapters.filter((row) => row.status !== "verified");
    if (pending.length) {
      console.log(
        `topics/${slug}: ${result.chapters.length - pending.length}/${result.chapters.length} chapters verified, status ${result.topicStatus}`,
      );
      break;
    }
    console.log(`✓ topics/${slug}: every chapter verified, status ${result.topicStatus}`);
    break;
  }

  default:
    fail(command ? `unknown command "${command}"` : "no command given");
}
