/**
 * Checks that a pinned excerpt still appears in the document it names.
 *
 * Every later check in this repo trusts `sources.json`. The faithfulness auditor
 * rules a claim against an excerpt, and `forge verify` confirms the auditor quoted
 * the excerpt correctly — but nothing until now confirmed the excerpt itself was
 * ever in the source. That is the one link in the chain where a fabrication enters
 * and never gets caught.
 *
 * This check is advisory on purpose. A published document is not a string: list
 * numbering is generated by stylesheets, tables carry rules a quotation reasonably
 * omits, and entities render as the characters they stand for. Those produce misses
 * that are artefacts of rendering rather than defects in the excerpt, which is why
 * the result is three-valued and why nothing here fails a build. What it is good at
 * is the case it was written for: a quote pinned to a URL whose document does not
 * contain it at all.
 */

export type ExcerptVerdict = "verbatim" | "spacing" | "missing";

export type SourceCheck = {
  id: string;
  url: string;
  fetched: boolean;
  note?: string;
  excerpts: { key: string; locator: string; verdict: ExcerptVerdict }[];
};

/** Fetches a URL and returns its body, or throws. Injected so tests need no network. */
export type FetchText = (url: string) => Promise<string>;

const ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: " ",
  mdash: "—",
  ndash: "–",
  hellip: "…",
};

/**
 * The running head an RFC repeats at the top of every page, matched on its full
 * shape — number, title, month, year — rather than on a leading "RFC", so a
 * sentence that happens to mention an RFC and a year survives.
 */
const RFC_RUNNING_HEAD =
  /RFC \d+\s{2,}\S[^\n]*?\s{2,}(?:January|February|March|April|May|June|July|August|September|October|November|December) (?:19|20)\d{2}/g;

/**
 * Reduces a fetched document to something a quotation can be looked up in: markup
 * removed, entities resolved, page furniture dropped. Tags become a space, which is
 * why the caller also compares with whitespace removed entirely.
 */
export function plainText(raw: string): string {
  return raw
    .replace(/<(script|style)[\s\S]*?<\/\1>/gi, " ")
    .replace(/\f/g, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&#(\d+);/g, (_, n: string) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n: string) => String.fromCodePoint(parseInt(n, 16)))
    .replace(/&([a-z]+);/gi, (whole: string, name: string) => ENTITIES[name.toLowerCase()] ?? whole)
    .replace(/.*\[Page \d+\]/g, " ")
    .replace(RFC_RUNNING_HEAD, " ");
}

/** Whitespace and case folded away. The comparison a faithful quote should survive. */
export function loose(text: string): string {
  return text.replace(/\s+/g, " ").trim().toLowerCase();
}

/**
 * Everything a renderer is entitled to change folded away as well: spacing, the
 * quotation-mark and dash families, compatibility forms, and list enumerators. A
 * quote that matches here and not under `loose` was copied from the rendered page
 * rather than the source text, which is a formatting difference and not a false
 * quotation.
 *
 * Enumerators earn their place: an ordered list's "1." is drawn by a stylesheet and
 * is absent from the document text, so every quotation of a numbered algorithm looks
 * fabricated without this. The pattern is deliberately narrow — a one or two digit
 * run, a dot, whitespace on both sides — because digits inside a quote are usually
 * the point. A specification's byte ranges must never be folded away in the name of
 * tidying up a list.
 *
 * The closing-bracket form was tried and removed. It matched the "10)" in a phrase
 * like "see security considerations (section 10) below", and since the page wrapped
 * that section number in a link, the document text read "10 )" and did not match
 * while the quote did. Any folding that fires on one side and not the other turns an
 * honest quote into a missing one, which is the failure this whole check exists to
 * detect.
 */
export function tight(text: string): string {
  return text
    .normalize("NFKC")
    .replace(/["'‘’‛“”]/g, "'")
    .replace(/[‐-―−]/g, "-")
    .replace(/(^|\s)\d{1,2}\.(?=\s)/g, " ")
    .replace(/\s+/g, "")
    .toLowerCase();
}

export function ruleOn(quote: string, document: string): ExcerptVerdict {
  const text = plainText(document);
  if (loose(text).includes(loose(quote))) return "verbatim";
  if (tight(text).includes(tight(quote))) return "spacing";
  return "missing";
}

export type SourceLike = {
  id: string;
  url: string;
  excerpts: { key: string; locator: string; quote: string }[];
};

/**
 * Rules on every excerpt of every source. A source that cannot be fetched is
 * recorded as unfetched rather than as a pile of missing excerpts, because those
 * are different findings and only one of them is about the excerpt.
 */
export async function checkSources(sources: SourceLike[], get: FetchText): Promise<SourceCheck[]> {
  const results: SourceCheck[] = [];
  for (const source of sources) {
    let body: string;
    try {
      body = await get(source.url);
    } catch (error) {
      results.push({
        id: source.id,
        url: source.url,
        fetched: false,
        note: error instanceof Error ? error.message : String(error),
        excerpts: [],
      });
      continue;
    }
    results.push({
      id: source.id,
      url: source.url,
      fetched: true,
      excerpts: source.excerpts.map((excerpt) => ({
        key: excerpt.key,
        locator: excerpt.locator,
        verdict: ruleOn(excerpt.quote, body),
      })),
    });
  }
  return results;
}

/** Long enough for a slow standards server, short enough that one dead host does not
 *  hold the whole check open. An unreachable source is a finding, not a reason to hang. */
const FETCH_TIMEOUT_MS = 20_000;

export const fetchText: FetchText = async (url) => {
  const response = await fetch(url, {
    headers: { "user-agent": "learning-forge" },
    redirect: "follow",
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  return await response.text();
};
